INSERT INTO `#__jd_configs` (`id`, `config_key`, `config_value`) VALUES
(1, 'option', 'com_jdonation'),
(2, 'view', 'configuration'),
(3, 'load_twitter_bootstrap', '0'),
(4, 'twitter_bootstrap_version', '5'),
(5, 'cb_integration', '0'),
(6, 'registration_integration', '0'),
(7, 'show_update_available_message_in_dashboard', '1'),
(8, 'create_account_when_donation_active', '1'),
(9, 'show_login_box', '0'),
(10, 'use_https', '0'),
(11, 'use_campaign', '1'),
(12, 'show_campaign', '0'),
(13, 'show_campaign_progress', '0'),
(14, 'show_campaign_picture', '0'),
(15, 'endable_donation_with_expired_campaigns', '0'),
(16, 'endable_donation_with_goal_achieved_campaigns', '0'),
(17, 'auto_approval_campaign', '0'),
(18, 'activate_campaign_currency', '0'),
(19, 'simple_language', '0'),
(20, 'enable_recurring', '1'),
(21, 'enable_cancel_recurring', '0'),
(22, 'recurring_frequencies', 'd,b,m,a'),
(23, 'currency_selection', '0'),
(24, 'active_currencies', 'USD'),
(25, 'convert_currency_before_donation', '0'),
(26, 'show_pending_records', '0'),
(27, 'enable_captcha', '0'),
(28, 'enable_captcha_with_public_user', '0'),
(29, 'block_ip_addresses', ''),
(30, 'show_r_times', '1'),
(31, 'convenience_fee', '0'),
(32, 'include_payment_fee', '0'),
(33, 'pay_payment_gateway_fee', '0'),
(34, 'field_campaign', '0'),
(35, 'amount_by_campaign', '0'),
(36, 'enable_hide_donor', '0'),
(37, 'amounts_format', '1'),
(38, 'minimum_donation_amount', '0'),
(39, 'maximum_donation_amount', '1000'),
(40, 'currency', 'USD'),
(41, 'currency_symbol', '$'),
(42, 'decimals', '2'),
(43, 'dec_point', '.'),
(44, 'thousands_sep', ','),
(45, 'currency_position', '0'),
(46, 'currency_space', '0'),
(47, 'default_country', ''),
(48, 'donation_amounts', '10\r\n40\r\n60\r\n80'),
(49, 'donation_amounts_explanation', ''),
(50, 'show_brackets', '0'),
(51, 'display_amount_textbox', '1'),
(52, 'populate_from_previous_donation', '0'),
(53, 'complete_url', ''),
(54, 'activate_tributes', '0'),
(55, 'dedicate_type', '1,2,3,4'),
(56, 'add_honoree_in_csv', '0'),
(57, 'send_email_to_honoree', '0'),
(58, 'export_donors', '0'),
(59, 'accept_term', '0'),
(60, 'article_id', '0'),
(61, 'show_newsletter_subscription', '0'),
(62, 'date_format', 'd-m-Y'),
(63, 'enable_gift_aid', '0'),
(64, 'allowed_extensions', 'doc, docx, ppt, pptx, pdf, zip, rar, jpg, jepg, png, zip'),
(65, 'upload_max_file_size', '2'),
(66, 'send_attachment_to_admin_email', '0'),
(67, 'number_segmenets', '5'),
(68, 'layout_type', '0'),
(69, 'default_layout', '1'),
(70, 'campaign_color', '7BB4E0'),
(71, 'csv_delimiter', ','),
(72, 'social_sharing', '1'),
(73, 'social_sharing_type', '0'),
(74, 'addthis_publisher', ''),
(75, 'color', 'B250D2'),
(76, 'display_field_description', 'not_showing'),
(77, 'show_payment_method', '0'),
(78, 'activate_form_floating', '0'),
(79, 'min_form_time', ''),
(80, 'max_form_submission', ''),
(81, 'from_name', ''),
(82, 'from_email', ''),
(83, 'reply_email', ''),
(84, 'notification_emails', ''),
(85, 'log_emails', '0'),
(86, 'paypal_redirect_message', ''),
(87, 'admin_email_subject', 'New Donation'),
(88, 'admin_email_body', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">You Have Received a New Donation!</h2>\r\n<p style=\"color: #222;\">Dear Administrator,</p>\r\n<p style=\"color: #222;\">A new donation has been made to your campaign. Here are the details:</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Campaign:</td>\r\n<td>[CAMPAIGN]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Donor Name:</td>\r\n<td>[FIRST_NAME] [LAST_NAME]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Organization:</td>\r\n<td>[ORGANIZATION]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Address:</td>\r\n<td>[ADDRESS] [ADDRESS2]<br />[CITY], [STATE] [ZIP]<br />[COUNTRY]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Phone:</td>\r\n<td>[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Fax:</td>\r\n<td>[FAX]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Email:</td>\r\n<td>[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Amount:</td>\r\n<td style=\"color: #388e3c; font-weight: bold;\">[AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Comment:</td>\r\n<td>[COMMENT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">This is an automated notification from your website. Please do not reply to this email.</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(89, 'user_email_subject', 'Donation Confirmation'),
(90, 'user_email_body', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">Thank You for Your Donation!</h2>\r\n<p style=\"color: #222;\">Dear [FIRST_NAME] [LAST_NAME],</p>\r\n<p style=\"color: #222;\">Thank you for your generous donation to our site. We appreciate your support.<br />Here are the details of your donation:</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Campaign:</td>\r\n<td>[CAMPAIGN]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Organization:</td>\r\n<td>[ORGANIZATION]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Address:</td>\r\n<td>[ADDRESS] [ADDRESS2]<br />[CITY], [STATE] [ZIP]<br />[COUNTRY]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Phone:</td>\r\n<td>[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Email:</td>\r\n<td>[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Amount:</td>\r\n<td style=\"color: #388e3c; font-weight: bold;\">[AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Comment:</td>\r\n<td>[COMMENT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #222; margin-top: 24px;\">If you have any questions, please contact us at [SITE_EMAIL].</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">Best regards,<br />Website Administrator Team</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(91, 'user_email_body_offline', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">Thank You for Your Donation!</h2>\r\n<p style=\"color: #222;\">Dear [FIRST_NAME] [LAST_NAME],</p>\r\n<p style=\"color: #222;\">Thank you for choosing to support our site with your generous donation.<br />Here are the details of your donation:</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Campaign:</td>\r\n<td>[CAMPAIGN]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Organization:</td>\r\n<td>[ORGANIZATION]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Address:</td>\r\n<td>[ADDRESS] [ADDRESS2]<br />[CITY], [STATE] [ZIP]<br />[COUNTRY]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Phone:</td>\r\n<td>[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Email:</td>\r\n<td>[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Amount:</td>\r\n<td style=\"color: #388e3c; font-weight: bold;\">[AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Comment:</td>\r\n<td>[COMMENT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<h3 style=\"color: #1a237e; margin-top: 32px;\">Offline Payment Instructions</h3>\r\n<p style=\"color: #222;\">Please send your donation as soon as possible to our bank account below:</p>\r\n<table style=\"background: #e3f2fd; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Account Name:</td>\r\n<td>Tuan Pham Ngoc</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Bank:</td>\r\n<td>Ngan Hang Ngoai Thuong Vietcombank</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Account Number:</td>\r\n<td>XXX045485467</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #222; margin-top: 18px;\">We look forward to receiving your payment. If you have any questions, please contact us at [SITE_EMAIL].</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">Best regards,<br />Website Administrator Team</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(92, 'user_email_body_offline_received', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">Your Donation Has Been Received!</h2>\r\n<p style=\"color: #222;\">Dear [FIRST_NAME] [LAST_NAME],</p>\r\n<p style=\"color: #222;\">We are pleased to inform you that we have received your donation via offline payment.<br />Thank you very much for your generous support!</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Campaign:</td>\r\n<td>[CAMPAIGN]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Amount:</td>\r\n<td style=\"color: #388e3c; font-weight: bold;\">[AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Date Received:</td>\r\n<td>[RECEIVED_DATE]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Comment:</td>\r\n<td>[COMMENT]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #222; margin-top: 24px;\">Your contribution makes a real difference. If you have any questions or need further assistance, please contact us at [SITE_EMAIL].</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">Once again, thank you for your support!<br />Best regards,<br />Website Administrator Team</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(93, 'recurring_email_subject', 'New Payment From Recurring Donation'),
(94, 'recurring_email_body', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">New Recurring Donation Processed</h2>\r\n<p style=\"color: #222;\">Hello Admin,</p>\r\n<p style=\"color: #222;\">A new payment has been received from a recurring donation.</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Donation Amount:</td>\r\n<td>[DONATION_AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Donor Name:</td>\r\n<td>[DONOR_NAME]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Date:</td>\r\n<td>[DATE]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #222; margin-top: 24px;\">You can <a style=\"color: #1976d2; text-decoration: underline;\" href=\"[DONATION_LINK]\">click here</a> to view the details of this donation record.</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">This is an automated notification from your website donation system.</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(95, 'cancel_recurring_email_subject', 'Recurring donation cancelled confirmation'),
(96, 'cancel_recurring_email_body', '<p>Dear <strong>[FIRST_NAME] [LAST_NAME]</strong></p>\r\n<p>Your recurring donation for plan <strong>[CAMPAIGN]</strong> has just been cancelled.</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(97, 'cancel_recurring_admin_email_subject', 'Recurring donation cancelled'),
(98, 'cancel_recurring_admin_email_body', '<p>Dear Administrator</p>\r\n<p>User <strong>[FIRST_NAME] [LAST_NAME]</strong> has just cancelled his recurring donation for <strong>[CAMPAIGN]</strong>.</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>'),
(99, 'donation_form_msg', '<p>Your support makes a difference! Please use this form to make your online donation. If you wish to support a specific cause or project, let us know in the comment box below</p>'),
(100, 'thanks_message', '<p><p>Thanks for making donation on our site</p></p>'),
(101, 'thanks_message_offline', '<p><p>Thanks for donating to our site .</p><br /><p>Please send the offline payment ASAP to our bank account . Information of our bank account is as follow :</p><br /><p><strong>Tuan Pham Ngoc, Ngan Hang Ngoai Thuong Vietcombank, Account Number XXX045485467</strong></p><br /><p>We are looking forward to receiving your payment .</p></p>'),
(102, 'cancel_message', '<p><p>Your donation has been cancelled</p></p>'),
(103, 'honoree_email_subject', 'Someone just gave donation in remembrance of you'),
(104, 'honoree_email_body', '<p>Dear [HONOREE_NAME],</p>\r\n<p>A donation was made in [DEDICATE_TYPE] [HONOREE_NAME] by [FIRST_NAME] [LAST_NAME]. The [AMOUNT] donation that [FIRST_NAME] made to the [CAMPAIGN] fund in your name will help our cause and be put to good use making a difference.</p>\r\n<p>With our thanks,</p>'),
(105, 'new_campaign_email_subject', 'New Campaign Submitted: [CAMPAIGN_TITLE]'),
(106, 'new_campaign_email_body', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #1976d2; margin-top: 0;\">New Campaign Created</h2>\r\n<p style=\"color: #222;\">Hello Admin,</p>\r\n<p style=\"color: #222;\">A new campaign has been submitted on your website.</p>\r\n<table style=\"background: #f8f9fb; border-radius: 6px;\" width=\"100%\" cellspacing=\"0\" cellpadding=\"6\">\r\n<tbody>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Campaign Title:</td>\r\n<td>[CAMPAIGN_TITLE]</td>\r\n</tr>\r\n<tr>\r\n<td style=\"font-weight: bold;\">Submitted By:</td>\r\n<td>[OWNER]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p style=\"color: #222; margin-top: 24px;\">You can <a style=\"color: #1976d2; text-decoration: underline;\" href=\"[CAMPAIGN_LINK]\">click here</a> to review the campaign details.</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">This is an automated notification from your website.</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(107, 'campaign_owner_notification', 'Congratulations! Your campaign [CAMPAIGN_TITLE] has received a new donation'),
(108, 'campaign_owner_notification_body', '<table style=\"max-width: 600px; margin: auto; background: #ffffff; border-radius: 8px; box-shadow: 0 2px 6px rgba(0,0,0,0.03);\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n<tbody>\r\n<tr>\r\n<td style=\"padding: 24px 32px;\">\r\n<h2 style=\"color: #388e3c; margin-top: 0;\">Great News!</h2>\r\n<p style=\"color: #222;\">Dear [OWNER],</p>\r\n<p style=\"color: #222;\">Your campaign <strong>[CAMPAIGN_TITLE]</strong> has just received a new donation!</p>\r\n<p style=\"color: #222;\">You can <a style=\"color: #1976d2; text-decoration: underline;\" href=\"[CAMPAIGN_LINK]\">click here</a> to view your campaign and see the details.</p>\r\n<p style=\"color: #222;\">Thank you for your efforts and dedication. We wish you continued success with your campaign!</p>\r\n<p style=\"color: #666; font-size: 13px; margin-top: 24px;\">This is an automated notification from your website.</p>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(109, 'payment_request_sbj', ''),
(110, 'payment_request_body', ''),
(111, 'activate_donation_receipt_feature', '0'),
(112, 'generated_invoice_for_paid_donation_only', '0'),
(113, 'invoice_readonly', '0'),
(114, 'send_receipt_via_email', '0'),
(115, 'send_receipt_to_admin', '0'),
(116, 'invoice_start_number', '1'),
(117, 'reset_invoice_number', '0'),
(118, 'invoice_prefix', ''),
(119, 'invoice_number_length', '5'),
(120, 'pdf_font', 'times'),
(121, 'donation_receipt_layout', '<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"100%\">\r\n<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td width=\"100%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Company Name:</td>\r\n<td align=\"left\">Ossolution Team</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">URL:</td>\r\n<td align=\"left\">http://www.joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:</td>\r\n<td align=\"left\">84-972409994</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">E-mail:</td>\r\n<td align=\"left\">contact@joomdonation.com</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Address:</td>\r\n<td align=\"left\">Lang Ha - Ba Dinh - Ha Noi</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align=\"right\" valign=\"middle\" width=\"50%\"><img style=\"border: 0;\" src=\"media/com_jdonation/invoice_logo.png\" border=\"0\" /></td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\" width=\"100%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Donor information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Name:</td>\r\n<td align=\"left\">[NAME]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Company:</td>\r\n<td align=\"left\">[ORGANIZATION]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Phone:?</td>\r\n<td align=\"left\">[PHONE]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Email:</td>\r\n<td align=\"left\">[EMAIL]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Address:</td>\r\n<td align=\"left\">[ADDRESS], [CITY], [STATE], [COUNTRY]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n<td align=\"left\" valign=\"top\" width=\"50%\">\r\n<table style=\"width: 100%;\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n<tbody>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Donation Information</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Donation Amount</td>\r\n<td align=\"left\">[AMOUNT]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">Donation Date Date:</td>\r\n<td align=\"left\">[DONATION_DATE]</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">?</td>\r\n<td align=\"left\">?</td>\r\n</tr>\r\n<tr>\r\n<td align=\"left\" width=\"50%\">?</td>\r\n<td align=\"left\">?</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td style=\"background-color: #d6d6d6;\" colspan=\"2\" align=\"left\">\r\n<h4 style=\"margin: 0px;\">Donation Details</h4>\r\n</td>\r\n</tr>\r\n<tr>\r\n<td colspan=\"2\" align=\"left\" width=\"100%\">[DONATION_DETAIL]</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</td>\r\n</tr>\r\n</tbody>\r\n</table>'),
(122, 'custom_css', ''),
(123, 'show_privacy', '0'),
(124, 'privacy_policy_article_id', ''),
(125, 'store_ip_address', '0'),
(126, 'download_id', ''),
(127, 'task', 'save');